# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noble.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'noble.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnoble.proto\x12\x05nobel\"P\n\x16\x43ountByCategoryRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nyear_start\x18\x02 \x01(\x05\x12\x10\n\x08year_end\x18\x03 \x01(\x05\"\"\n\x12\x43ountByYearRequest\x12\x0c\n\x04year\x18\x01 \x01(\x05\"\x1e\n\rCountResponse\x12\r\n\x05total\x18\x01 \x01(\x05\"-\n\x18SearchByFirstnameRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\"I\n\x03Hit\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\x0f\n\x07surname\x18\x04 \x01(\t\")\n\rSearchResults\x12\x18\n\x04hits\x18\x01 \x03(\x0b\x32\n.nobel.Hit\"+\n\x18\x43ountByMotivationRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"5\n\x0f\x46ullNameRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"A\n\x0b\x46ullNameHit\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t\"3\n\x0f\x46ullNameResults\x12 \n\x04hits\x18\x01 \x03(\x0b\x32\x12.nobel.FullNameHit2\xed\x02\n\nNobelQuery\x12\x46\n\x0f\x43ountByCategory\x12\x1d.nobel.CountByCategoryRequest\x1a\x14.nobel.CountResponse\x12>\n\x0b\x43ountByYear\x12\x19.nobel.CountByYearRequest\x1a\x14.nobel.CountResponse\x12J\n\x11SearchByFirstname\x12\x1f.nobel.SearchByFirstnameRequest\x1a\x14.nobel.SearchResults\x12J\n\x11\x43ountByMotivation\x12\x1f.nobel.CountByMotivationRequest\x1a\x14.nobel.CountResponse\x12?\n\rGetByFullName\x12\x16.nobel.FullNameRequest\x1a\x16.nobel.FullNameResultsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noble_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COUNTBYCATEGORYREQUEST']._serialized_start=22
  _globals['_COUNTBYCATEGORYREQUEST']._serialized_end=102
  _globals['_COUNTBYYEARREQUEST']._serialized_start=104
  _globals['_COUNTBYYEARREQUEST']._serialized_end=138
  _globals['_COUNTRESPONSE']._serialized_start=140
  _globals['_COUNTRESPONSE']._serialized_end=170
  _globals['_SEARCHBYFIRSTNAMEREQUEST']._serialized_start=172
  _globals['_SEARCHBYFIRSTNAMEREQUEST']._serialized_end=217
  _globals['_HIT']._serialized_start=219
  _globals['_HIT']._serialized_end=292
  _globals['_SEARCHRESULTS']._serialized_start=294
  _globals['_SEARCHRESULTS']._serialized_end=335
  _globals['_COUNTBYMOTIVATIONREQUEST']._serialized_start=337
  _globals['_COUNTBYMOTIVATIONREQUEST']._serialized_end=380
  _globals['_FULLNAMEREQUEST']._serialized_start=382
  _globals['_FULLNAMEREQUEST']._serialized_end=435
  _globals['_FULLNAMEHIT']._serialized_start=437
  _globals['_FULLNAMEHIT']._serialized_end=502
  _globals['_FULLNAMERESULTS']._serialized_start=504
  _globals['_FULLNAMERESULTS']._serialized_end=555
  _globals['_NOBELQUERY']._serialized_start=558
  _globals['_NOBELQUERY']._serialized_end=923
# @@protoc_insertion_point(module_scope)
