# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import noble_pb2 as noble__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in noble_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelQueryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountByCategory = channel.unary_unary(
                '/nobel.NobelQuery/CountByCategory',
                request_serializer=noble__pb2.CountByCategoryRequest.SerializeToString,
                response_deserializer=noble__pb2.CountResponse.FromString,
                _registered_method=True)
        self.CountByYear = channel.unary_unary(
                '/nobel.NobelQuery/CountByYear',
                request_serializer=noble__pb2.CountByYearRequest.SerializeToString,
                response_deserializer=noble__pb2.CountResponse.FromString,
                _registered_method=True)
        self.SearchByFirstname = channel.unary_unary(
                '/nobel.NobelQuery/SearchByFirstname',
                request_serializer=noble__pb2.SearchByFirstnameRequest.SerializeToString,
                response_deserializer=noble__pb2.SearchResults.FromString,
                _registered_method=True)
        self.CountByMotivation = channel.unary_unary(
                '/nobel.NobelQuery/CountByMotivation',
                request_serializer=noble__pb2.CountByMotivationRequest.SerializeToString,
                response_deserializer=noble__pb2.CountResponse.FromString,
                _registered_method=True)
        self.GetByFullName = channel.unary_unary(
                '/nobel.NobelQuery/GetByFullName',
                request_serializer=noble__pb2.FullNameRequest.SerializeToString,
                response_deserializer=noble__pb2.FullNameResults.FromString,
                _registered_method=True)


class NobelQueryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountByCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountByYear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByFirstname(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountByMotivation(self, request, context):
        """NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByFullName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CountByCategory,
                    request_deserializer=noble__pb2.CountByCategoryRequest.FromString,
                    response_serializer=noble__pb2.CountResponse.SerializeToString,
            ),
            'CountByYear': grpc.unary_unary_rpc_method_handler(
                    servicer.CountByYear,
                    request_deserializer=noble__pb2.CountByYearRequest.FromString,
                    response_serializer=noble__pb2.CountResponse.SerializeToString,
            ),
            'SearchByFirstname': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByFirstname,
                    request_deserializer=noble__pb2.SearchByFirstnameRequest.FromString,
                    response_serializer=noble__pb2.SearchResults.SerializeToString,
            ),
            'CountByMotivation': grpc.unary_unary_rpc_method_handler(
                    servicer.CountByMotivation,
                    request_deserializer=noble__pb2.CountByMotivationRequest.FromString,
                    response_serializer=noble__pb2.CountResponse.SerializeToString,
            ),
            'GetByFullName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByFullName,
                    request_deserializer=noble__pb2.FullNameRequest.FromString,
                    response_serializer=noble__pb2.FullNameResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobel.NobelQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobel.NobelQuery', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelQuery(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelQuery/CountByCategory',
            noble__pb2.CountByCategoryRequest.SerializeToString,
            noble__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountByYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelQuery/CountByYear',
            noble__pb2.CountByYearRequest.SerializeToString,
            noble__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByFirstname(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelQuery/SearchByFirstname',
            noble__pb2.SearchByFirstnameRequest.SerializeToString,
            noble__pb2.SearchResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountByMotivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelQuery/CountByMotivation',
            noble__pb2.CountByMotivationRequest.SerializeToString,
            noble__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByFullName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobel.NobelQuery/GetByFullName',
            noble__pb2.FullNameRequest.SerializeToString,
            noble__pb2.FullNameResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
